FROM oven/bun:1.3.2-slim

RUN apt-get update && apt-get install -y curl unzip git

RUN curl -fsSL https://opencode.ai/install | bash

# Copy entrypoint script
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

# Set the default command
EXPOSE 8080
ENTRYPOINT ["/app/entrypoint.sh"] 