FROM oven/bun:1.3.2-slim

RUN apt-get update && apt-get install -y curl unzip

RUN curl -fsSL https://opencode.ai/install | bash

# Set the default command with full path
EXPOSE 8080
CMD ["/root/.opencode/bin/opencode", "serve", "--hostname", "::", "--port", "42069"] 